spring:
  application:
    name: stock_dividend

  redis:
    host: localhost
    port: 6379

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true;

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:guiwoo;DB_CLOSE_DELAY=-1
    username: sa
    password:

  jwt:
    secret: SGV5TGlzdGVuTW90aGVyRnVja2VyV2hvRnVja2VkVXBSZXZpZXdMaWtlVGhhdEh1aFlvdVN1Y2hBSWRpb3RGdWNraW5nUmV0YXJk

scheduler:
  scrape:
    yahoo: "0 0 0 * * *"

